valor = input('Digite algo: ')
print ('Esse é o tipo primitivo de {}:'.format(valor), type(valor))
print('Alfanumérico?', valor.isalnum())
print('Alfabético?', valor.isalpha())
print('Numérico?', valor.isnumeric())
print('Maiúsculo?', valor.isupper())
print('Minúsculo?', valor.islower())
print('Captalizada?', valor.istitle())
print('Espaços?', valor.isspace())
print('Imprimível?', valor.isprintable())
